'use client'
import { createContext, useContext, useState, ReactNode } from 'react'

export type Lang = 'en' | 'hi' | 'mr'

const STRINGS: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    nav_explore: 'Explore Crops',
    nav_login: 'Login',
    nav_signup: 'Sign up',
    // Home
    hero_title: "Don't just buy the harvest.",
    hero_title_hl: 'Experience the journey behind it.',
    story1_title: 'Choose a Crop',
    story1_desc: 'Pick a real crop growing on a real, verified farm near you.',
    story2_title: 'Follow the Journey',
    story2_desc: 'Get weekly, GPS-verified updates straight from the farmer, from sowing to growth.',
    story3_title: 'Own the Harvest',
    story3_desc: 'Receive your verified allocation, along with a CropPass™ proving every step of the journey.',
    // Signup
    signup_heading: 'Join FARMiLIVE',
    signup_customer: 'Customer',
    signup_farmer: 'Farmer',
    signup_name: 'Name',
    signup_email: 'Email',
    signup_mobile: 'Mobile',
    signup_password: 'Password (min 6 characters)',
    signup_btn: 'Create account',
    // Login
    login_heading: 'Log in to FARMiLIVE',
    login_btn: 'Log in',
    login_no_account: "No account?",
    login_signup_link: 'Sign up',
    // Crops browse
    crops_heading: 'Explore Crops',
    crops_sub: 'Choose a crop, follow its journey, own the harvest.',
    crops_none: 'No approved crops yet — check back soon.',
    crops_location: 'Location',
    crops_stage: 'Current stage',
    crops_harvest: 'Expected harvest',
    crops_slots: 'slots reserved',
    // Crop detail
    detail_sowing_date: 'Sowing date',
    detail_expected_harvest: 'Expected harvest',
    detail_expected_alloc: 'Expected allocation for you',
    detail_slots: 'Slots',
    detail_ack: "I understand this is an expected allocation. Final quantity depends on the actual verified harvest, per the published formula: Payout = min(Actual, Expected) × Price + Shortfall × Refund%. I pay only after harvest, plus a refundable ₹99 booking token now.",
    detail_reserve_btn: 'Reserve with ₹99 (refundable)',
    detail_reserving: 'Reserving...',
    detail_updates_heading: 'Verified Crop Updates',
    detail_updates_none: 'No verified updates yet — check back soon.',
    detail_location_verified: 'Farm location verified',
    // Farmer dashboard
    farmer_dashboard: 'Farmer Dashboard',
    farmer_guide_link: 'Open Farming Guide',
    farmer_no_farm: "You haven't registered a farm yet. Add one below.",
    farmer_farm_name: 'Farm name (e.g. Patil Family Farm)',
    farmer_district: 'District (e.g. Pune District)',
    farmer_lat: 'Latitude (e.g. 18.7608)',
    farmer_lon: 'Longitude (e.g. 73.8630)',
    farmer_area: 'Farm area in acres (e.g. 3)',
    farmer_register_btn: 'Register Farm',
    farmer_approved: 'Approved',
    farmer_pending: 'Pending admin approval',
    farmer_my_crops: 'My Crops',
    farmer_add_crop: '+ Add Crop',
    farmer_no_crops: 'No crops listed yet.',
    farmer_stage: 'Stage',
    farmer_slots_reserved: 'slots reserved',
    farmer_submit_update: 'Submit Weekly Update',
    // Customer dashboard
    customer_my_subs: 'My Subscriptions',
    customer_none: 'No subscriptions yet — go explore crops!',
    customer_status: 'Status',
    customer_expected_alloc: 'Expected allocation',
    customer_final_alloc: 'Final verified allocation',
    customer_shortfall: 'Shortfall',
    customer_refund: 'Refund',
    customer_crop_pass: 'Your CropPass™ — scan to view the verified journey',
    customer_waiting: 'Waiting for harvest to be recorded...',
    // Farming guide
    guide_heading: 'Farming Guide — Wheat',
    guide_sub: 'Practical tips by growth stage, adapted from ICAR and established IPM practice.',
    guide_organic: 'Organic-first',
    guide_conventional: 'Conventional (ICAR)',
    guide_source: 'Source',
    guide_ask_heading: 'Ask a question',
    guide_ask_placeholder: 'e.g. My wheat leaves are turning yellow, what should I do?',
    guide_ask_btn: 'Ask',
    guide_asking: 'Asking...',
    guide_disclaimer: "These guides are general agricultural information adapted from ICAR and established IPM practice. They are not a substitute for your local Krishi Vigyan Kendra's advice, product labels, or a soil test. Always follow product label instructions for any chemical input.",
  },
  hi: {
    nav_explore: 'फ़सलें देखें',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
    hero_title: 'सिर्फ़ फ़सल मत खरीदिए।',
    hero_title_hl: 'उसके पीछे की यात्रा को अनुभव कीजिए।',
    story1_title: 'फ़सल चुनें',
    story1_desc: 'अपने पास किसी असली, सत्यापित खेत पर उगने वाली फ़सल चुनें।',
    story2_title: 'यात्रा को फ़ॉलो करें',
    story2_desc: 'बुआई से वृद्धि तक, किसान से सीधे साप्ताहिक, GPS-सत्यापित अपडेट पाएँ।',
    story3_title: 'फ़सल के मालिक बनें',
    story3_desc: 'अपना सत्यापित आवंटन पाएँ, साथ में एक CropPass™ जो पूरी यात्रा साबित करता है।',
    signup_heading: 'FARMiLIVE से जुड़ें',
    signup_customer: 'ग्राहक',
    signup_farmer: 'किसान',
    signup_name: 'नाम',
    signup_email: 'ईमेल',
    signup_mobile: 'मोबाइल',
    signup_password: 'पासवर्ड (कम से कम 6 अक्षर)',
    signup_btn: 'खाता बनाएं',
    login_heading: 'FARMiLIVE में लॉगिन करें',
    login_btn: 'लॉगिन',
    login_no_account: 'खाता नहीं है?',
    login_signup_link: 'साइन अप करें',
    crops_heading: 'फ़सलें देखें',
    crops_sub: 'एक फ़सल चुनें, उसकी यात्रा देखें, फ़सल के मालिक बनें।',
    crops_none: 'अभी कोई स्वीकृत फ़सल नहीं है — बाद में देखें।',
    crops_location: 'स्थान',
    crops_stage: 'वर्तमान चरण',
    crops_harvest: 'अनुमानित कटाई',
    crops_slots: 'स्लॉट आरक्षित',
    detail_sowing_date: 'बुआई तिथि',
    detail_expected_harvest: 'अनुमानित कटाई',
    detail_expected_alloc: 'आपके लिए अनुमानित आवंटन',
    detail_slots: 'स्लॉट',
    detail_ack: 'मैं समझता/समझती हूँ कि यह एक अनुमानित आवंटन है। अंतिम मात्रा वास्तविक सत्यापित कटाई पर निर्भर करती है, प्रकाशित सूत्र के अनुसार: भुगतान = min(वास्तविक, अनुमानित) × मूल्य + कमी × वापसी%। मैं कटाई के बाद ही भुगतान करता/करती हूँ, अभी सिर्फ़ ₹99 का वापसी योग्य टोकन।',
    detail_reserve_btn: '₹99 से रिज़र्व करें (वापसी योग्य)',
    detail_reserving: 'रिज़र्व हो रहा है...',
    detail_updates_heading: 'सत्यापित फ़सल अपडेट',
    detail_updates_none: 'अभी कोई सत्यापित अपडेट नहीं है — बाद में देखें।',
    detail_location_verified: 'खेत का स्थान सत्यापित',
    farmer_dashboard: 'किसान डैशबोर्ड',
    farmer_guide_link: 'खेती गाइड खोलें',
    farmer_no_farm: 'आपने अभी तक कोई खेत दर्ज नहीं किया है। नीचे एक जोड़ें।',
    farmer_farm_name: 'खेत का नाम (जैसे Patil Family Farm)',
    farmer_district: 'ज़िला (जैसे पुणे ज़िला)',
    farmer_lat: 'लैटिट्यूड (जैसे 18.7608)',
    farmer_lon: 'लॉन्गिट्यूड (जैसे 73.8630)',
    farmer_area: 'खेत का क्षेत्रफल एकड़ में (जैसे 3)',
    farmer_register_btn: 'खेत दर्ज करें',
    farmer_approved: 'स्वीकृत',
    farmer_pending: 'एडमिन अनुमोदन लंबित',
    farmer_my_crops: 'मेरी फसलें',
    farmer_add_crop: '+ फसल जोड़ें',
    farmer_no_crops: 'अभी कोई फसल दर्ज नहीं है।',
    farmer_stage: 'चरण',
    farmer_slots_reserved: 'स्लॉट आरक्षित',
    farmer_submit_update: 'साप्ताहिक अपडेट भेजें',
    customer_my_subs: 'मेरी सब्सक्रिप्शन',
    customer_none: 'अभी कोई सब्सक्रिप्शन नहीं है — फ़सलें देखें!',
    customer_status: 'स्थिति',
    customer_expected_alloc: 'अनुमानित आवंटन',
    customer_final_alloc: 'अंतिम सत्यापित आवंटन',
    customer_shortfall: 'कमी',
    customer_refund: 'वापसी',
    customer_crop_pass: 'आपका CropPass™ — सत्यापित यात्रा देखने के लिए स्कैन करें',
    customer_waiting: 'कटाई दर्ज होने का इंतज़ार है...',
    guide_heading: 'खेती गाइड — गेहूँ',
    guide_sub: 'ICAR और स्थापित IPM पद्धति से अनुकूलित, विकास चरण अनुसार व्यावहारिक सुझाव।',
    guide_organic: 'जैविक-प्रथम',
    guide_conventional: 'परंपरागत (ICAR)',
    guide_source: 'स्रोत',
    guide_ask_heading: 'प्रश्न पूछें',
    guide_ask_placeholder: 'जैसे मेरे गेहूँ के पत्ते पीले हो रहे हैं, क्या करूँ?',
    guide_ask_btn: 'पूछें',
    guide_asking: 'पूछ रहे हैं...',
    guide_disclaimer: 'ये गाइड ICAR और स्थापित IPM पद्धति से अनुकूलित सामान्य कृषि जानकारी हैं। यह आपके स्थानीय कृषि विज्ञान केंद्र की सलाह, उत्पाद लेबल या मृदा परीक्षण का विकल्प नहीं है। किसी भी रासायनिक इनपुट के लिए हमेशा उत्पाद लेबल के निर्देशों का पालन करें।',
  },
  mr: {
    nav_explore: 'पिके पहा',
    nav_login: 'लॉगिन',
    nav_signup: 'साइन अप',
    hero_title: 'फक्त पीक विकत घेऊ नका.',
    hero_title_hl: 'त्यामागचा प्रवास अनुभवा.',
    story1_title: 'पीक निवडा',
    story1_desc: 'तुमच्या जवळील खऱ्या, सत्यापित शेतावर वाढणारे पीक निवडा.',
    story2_title: 'प्रवास फॉलो करा',
    story2_desc: 'पेरणीपासून वाढीपर्यंत, शेतकऱ्याकडून थेट साप्ताहिक, GPS-सत्यापित अपडेट मिळवा.',
    story3_title: 'पिकाचे मालक व्हा',
    story3_desc: 'तुमचे सत्यापित वाटप मिळवा, सोबत संपूर्ण प्रवास सिद्ध करणारा CropPass™.',
    signup_heading: 'FARMiLIVE मध्ये सामील व्हा',
    signup_customer: 'ग्राहक',
    signup_farmer: 'शेतकरी',
    signup_name: 'नाव',
    signup_email: 'ईमेल',
    signup_mobile: 'मोबाइल',
    signup_password: 'पासवर्ड (किमान 6 अक्षरे)',
    signup_btn: 'खाते तयार करा',
    login_heading: 'FARMiLIVE मध्ये लॉगिन करा',
    login_btn: 'लॉगिन',
    login_no_account: 'खाते नाही?',
    login_signup_link: 'साइन अप करा',
    crops_heading: 'पिके पहा',
    crops_sub: 'एक पीक निवडा, त्याचा प्रवास पहा, पिकाचे मालक व्हा.',
    crops_none: 'अजून कोणतेही मंजूर पीक नाही — नंतर पहा.',
    crops_location: 'स्थान',
    crops_stage: 'सध्याचा टप्पा',
    crops_harvest: 'अपेक्षित कापणी',
    crops_slots: 'स्लॉट राखीव',
    detail_sowing_date: 'पेरणी तारीख',
    detail_expected_harvest: 'अपेक्षित कापणी',
    detail_expected_alloc: 'तुमच्यासाठी अपेक्षित वाटप',
    detail_slots: 'स्लॉट',
    detail_ack: 'मला समजते की हे अपेक्षित वाटप आहे. अंतिम प्रमाण प्रत्यक्ष सत्यापित कापणीवर अवलंबून आहे, प्रसिद्ध सूत्रानुसार: मोबदला = min(प्रत्यक्ष, अपेक्षित) × किंमत + तूट × परतावा%. मी कापणीनंतरच मोबदला देतो/देते, आत्ता फक्त ₹99 चे परत मिळणारे टोकन.',
    detail_reserve_btn: '₹99 ने राखीव करा (परत मिळणारे)',
    detail_reserving: 'राखीव करत आहे...',
    detail_updates_heading: 'सत्यापित पीक अपडेट',
    detail_updates_none: 'अजून सत्यापित अपडेट नाही — नंतर पहा.',
    detail_location_verified: 'शेताचे स्थान सत्यापित',
    farmer_dashboard: 'शेतकरी डॅशबोर्ड',
    farmer_guide_link: 'शेती मार्गदर्शक उघडा',
    farmer_no_farm: 'तुम्ही अजून शेत नोंदवलेले नाही. खाली एक जोडा.',
    farmer_farm_name: 'शेताचे नाव (उदा. Patil Family Farm)',
    farmer_district: 'जिल्हा (उदा. पुणे जिल्हा)',
    farmer_lat: 'लॅटिट्यूड (उदा. 18.7608)',
    farmer_lon: 'लॉन्गिट्यूड (उदा. 73.8630)',
    farmer_area: 'शेताचे क्षेत्रफळ एकरात (उदा. 3)',
    farmer_register_btn: 'शेत नोंदवा',
    farmer_approved: 'मंजूर',
    farmer_pending: 'ॲडमिन मंजुरी प्रलंबित',
    farmer_my_crops: 'माझी पिके',
    farmer_add_crop: '+ पीक जोडा',
    farmer_no_crops: 'अजून कोणतेही पीक नोंदवलेले नाही.',
    farmer_stage: 'टप्पा',
    farmer_slots_reserved: 'स्लॉट राखीव',
    farmer_submit_update: 'साप्ताहिक अपडेट पाठवा',
    customer_my_subs: 'माझी सबस्क्रिप्शन',
    customer_none: 'अजून कोणतीही सबस्क्रिप्शन नाही — पिके पहा!',
    customer_status: 'स्थिती',
    customer_expected_alloc: 'अपेक्षित वाटप',
    customer_final_alloc: 'अंतिम सत्यापित वाटप',
    customer_shortfall: 'तूट',
    customer_refund: 'परतावा',
    customer_crop_pass: 'तुमचा CropPass™ — सत्यापित प्रवास पाहण्यासाठी स्कॅन करा',
    customer_waiting: 'कापणी नोंदवण्याची वाट पाहत आहे...',
    guide_heading: 'शेती मार्गदर्शक — गहू',
    guide_sub: 'ICAR आणि प्रस्थापित IPM पद्धतीवरून अनुकूलित, वाढीच्या टप्प्यानुसार व्यावहारिक सल्ला.',
    guide_organic: 'सेंद्रिय-प्रथम',
    guide_conventional: 'परंपरागत (ICAR)',
    guide_source: 'स्रोत',
    guide_ask_heading: 'प्रश्न विचारा',
    guide_ask_placeholder: 'उदा. माझ्या गव्हाची पाने पिवळी पडत आहेत, काय करू?',
    guide_ask_btn: 'विचारा',
    guide_asking: 'विचारत आहे...',
    guide_disclaimer: 'हे मार्गदर्शक ICAR आणि प्रस्थापित IPM पद्धतीवरून अनुकूलित सामान्य कृषी माहिती आहे. हे तुमच्या स्थानिक कृषी विज्ञान केंद्राच्या सल्ल्याचा, उत्पादन लेबलचा किंवा माती परीक्षणाचा पर्याय नाही. कोणत्याही रासायनिक इनपुटसाठी नेहमी उत्पादन लेबलच्या सूचनांचे पालन करा.',
  },
}

type LangContextType = {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LangContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')

  function t(key: string) {
    return STRINGS[lang][key] || STRINGS.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider')
  return ctx
}